#!/bin/zsh

# Language="None"
# Year="None"
# Day="None"

# New : create new folder with language
# get (year, day) : Get input
# submit (year day part): Send input

function test(){
	echo "Hello?"
}

function new() {
	mkdir -p $1
	touch $1"/lang"
	echo $2 >> $1"/lang"
}

function get(){
	mkdir -p $1
	mkdir -p $1/"day_"$(printf "%02d" $2)
	curl --cookie ~/aoc_cookies.txt -o $1/"day_"$(printf "%02d" $2)"/input" \https://adventofcode.com/$1/day/$(printf "%d" $2)/input
}

function submit() {
	curl --cookie ~/aoc_cookies.txt -o response.txt -X POST https://adventofcode.com/$1/day/$(printf "%d" $2)/answer -H "Content-Type: application/x-www-form-urlencoded" -d "level="$3"&answer="$4
}

function run() {
	cd $1
	lang=$(cat lang)
	cd "day_"$(printf "%02d" $2)
	if [ $lang = "c" ]
	then
		gcc -g -fsanitize=address -lm p$3.c && ./a.out
	else
		python3 p$3.py
	fi
}

# echo "Hello "$#

if declare -f "$1" > /dev/null
then
  "$@"
else
  echo "'$1' does not exist.\nUsage : ./aoc new [year] [lang] \n./aoc get [year] [day]\n./aoc run [year] [day] [level] ./aoc submit [year] [day] [level] [answer]" >&2
  exit 1
fi
# if [ $# != 3 ]
# then
# 	echo "Usage: ./Start.sh [Language] [Year] [Day]"
# 	exit
# fi

# Thi will do for now, but a better approach would be to get all folders  by name as they represent the langauges used, insted of manual typing each of them
# if [ $1 = "Python" ] || [ $1 = "C" ]
# then
# 	Language=$1
# else
# 	echo "Available languages are : Python, C"
# 	exit
# fi

# if [ $2 -lt 2015 ] || [ $2 -gt 2020 ]
# then
# 	echo "Invalid year. Available years are : 2015, 2016, 2017, 2018, 2019, 2020"
# 	exit
# else
# 	Year=$2
# fi

# if [ $3 -lt 1 ] || [ $3 -gt 25 ]
# then
# 	echo "Invalid day. Valid days range from 1 to 25"
# 	exit
# else
# 	Day="day_"$(printf "%02d" $3)
# fi

# mkdir -p $Language/$Year/$Day

# cd $Language/$Year/$Day

# if [ $Language = "C" ]
# then
# 	touch p1.c p2.c
# else
# 	touch p1.py p2.py
# fi

# curl --cookie ~/aoc_cookies.txt -o input \https://adventofcode.com/$Year/day/$(printf "%d" $3)/input
